version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/dbfdatareader/api/v2/package
  api_key:
    secure: Txy0mqrnu+yAYmJUOeEEasYrBeueDP1aKIleayisMXTS3/8F9+scL0TnBCseWdyx
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: fA+cdD+BnlYB7hX3xgjDEUc3q3aUoryIv6zVQUqrxxBkmPG00GJkzBnxbbWzSr1u
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: true
